name: Python CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Comprobar que existe el CSV
        run: |
          ls -lh datos/crudos/
          head -5 datos/crudos/obres_espai_public.csv

      - name: Ejecutar transformación
        run: |
          python codigo/transformacion/02_limpiar_obras.py

      - name: Crear base de datos
        run: |
          python codigo/carga/06_crear_bd.py

      - name: Cargar datos
        run: |
          python codigo/carga/07_cargar_obras.py

      - name: Ejecutar consultas SQL
        run: |
          python codigo/carga/08_consultas_sql.py

      - name: Generar dashboard
        run: |
          python codigo/visualizacion/05_dashboard_obras.py

      - name: Ejecutar pruebas
        run: |
          pytest -v